### PR TITLE
Jh/mobile pwa

### PR DESCRIPTION
**Pull request by Hiro-Nakamura**
## Release Notes

- [add] Mobile PWA Builder : provide QR code generation for mobile apps

### CODE REVIEW

**Review by guyyoo — APPROVED** [review]
LGTM!

**Review by nh758 — COMMENTED** [review]
This looks fine, but I'm questioning if we should put this here? It's not related to relay, other than we have the QR code generation for our existing relay apps.

Should we move QR code generation to another service (maybe definition manager?) and use that for both this and relay apps?

**Comment by Hiro-Nakamura** [comment]
Actually, I think it would be better to have it in it's own service, and have the Relay and mobile qr code request QR codes from there.  

But for now, this is where the QR code resided and this was the quickest method to get it up and running.  Maybe in the future we can pull this out and make it separate.

**Review by nh758 — APPROVED** [review]
Ok opened #31

**Pull request merged**
